version: '2.2'
services:
  jupyter_pyspark:
    build:
        context: ./
        dockerfile: jupyter_pyspark.Dockerfile
   # volumes:
   #     - /home/jovyan:/home/jovyan
    shm_size: 1G
    environment:
      - GRANT_SUDO=yes
   #   - PASSWORD=
    restart: always
   # restart: on-failure
    ports:
        - "8888:8888"
        - "4040:4040"
        - "4041:4041"
